### ISSUE TITLE
Add factory firmware

### ISSUE THREAD

**Issue by devnoname120** [joel16/VITAident#15]
See the following code for reference: https://github.com/TheOfficialFloW/modoru/blob/e74ce4f0c4c9e87866318123556a2460368d0c90/kernel.c#L306-L318

**Comment by joel16** [comment]
Haven't maintained this in a while lol. Perhaps it's time for an update, thanks for the suggestion!

**Comment by joel16** [comment]
Fixed with https://github.com/joel16/VITAident/commit/c4ca7838cf0eac5a5268d7a50ea2654e625ddf5b.
