### ISSUE TITLE
GUI start up C2-12828-1 after henkaku has been run

### ISSUE THREAD

**Issue by sergiogamboa2** [joel16/VITAident#2]
Hello i have a problem it is not working on neither my PS vita fat white and my ps vita slim black both US versions and I ran Tai henkaku from the beta.henkaku.xyz and after that ran the GUI version of vitaident and crash. attached the two crash in different times (I tried restarting the vitas)

By the way I had to add the .pdf to the crash files the vita generated because GitHub would not let me upload them.
[psp2core-1483601302-0x00000337a1-eboot.bin.psp2dmp.pdf](https://github.com/joel16/VITAident/files/686655/psp2core-1483601302-0x00000337a1-eboot.bin.psp2dmp.pdf)
[psp2core-1483601192-0x0000073e4f-eboot.bin.psp2dmp.pdf](https://github.com/joel16/VITAident/files/686656/psp2core-1483601192-0x0000073e4f-eboot.bin.psp2dmp.pdf)

**Comment by sergiogamboa2** [comment]
Non-gui works wonders thanks for the amazing work as always Joel!

**Comment by joel16** [comment]
Did you download the VID000016.zip file, and extract the VID000016 folder into ux0:/data/ ?
So it should be
ux0:/data/VID000016/

**Comment by sergiogamboa2** [comment]
Yes it was there however it was a previous version with a .bmp and dumb me were not smart enough to updated it, sorry to bother thanks for answering.
