### ISSUE TITLE
Possible to change PSN Username?

### ISSUE THREAD

**Issue by chris2ferz** [joel16/VITAident#3]
Recently changed memory cards.
PSN name defaulted to user700
This app detects that username.
Is it possible and safe to change this?
Unable to log into PSN for it to change back to what it was.

**Comment by joel16** [comment]
Hmm, you wouldn't be able to use this app for that. Maybe try https://github.com/some1psv/RegistryEditor

You might wanna ask around though just to be safe.  You can get some answers on r/vitahacks or wololo.net/talk

**Comment by chris2ferz** [comment]
I appreciate your fast reply and even better you helped me solve my issue.
That registry app was perfect for what I wanted to do.
Applied the change and it's back to my PSN name.
Thanks so much!
 
 
 
-----Original Message-----

**Comment by joel16** [comment]
No problem, thanks for using my software!
