### ISSUE TITLE
nonsensical code under id.dat menu

### ISSUE THREAD

**Issue by masterrite** [joel16/VITAident#4]
Hi,

I got a weird nonsensical string under the id.dat tab in vitaident 0.7 GUI. Is it supposed to be like this (I assume not).
![2017-02-10-131551](https://cloud.githubusercontent.com/assets/20837366/22840564/993c526c-ef93-11e6-9f8e-4e35c5fa0e7b.jpg)

Thanks!

**Comment by joel16** [comment]
Nope thats definitely not how it should be. Have you used any homebrew like easy adrenaline installer?

**Comment by masterrite** [comment]
Actually, I'm sorry - I restarted my vita just now and it refreshed its database. Then I reinstalled taihen and it works now.

**Comment by joel16** [comment]
Oh yeah that should regenerate id.dat I believe. No worries thanks for reporting!
