### ISSUE TITLE
use detected Enter button to exit

### ISSUE THREAD

**Issue by WanderMax** [joel16/VITAident#6]
In the app, it detects that the Enter button is O, and I use button-swapper to change it from original X.
When trigger the Exit menu, it still use the original X.
Could you please use the detected Enter button to trigger Exit?
Thanks

**Comment by joel16** [comment]
Well that's because it's hard coded to use the cross button to exit. I don't mind looking into your suggestion though, should be a simple fix.

**Comment by joel16** [comment]
I'm assuming you're using the GUI version since you're asking about the enter button. (If you were using the original you can press any button to exit so it shouldn't matter)

Anyways fixed https://github.com/joel16/VITAident/commit/897c6202ef80dbbaf39b306a91439347b9cf8b1d.

**Comment by WanderMax** [comment]
Thanks for your great tool!

**Comment by joel16** [comment]
No probs, I'll release an update with the following changes after I do add a bit more to it.
