### ISSUE TITLE
Dump CID

### ISSUE THREAD

**Issue by chronoss09** [joel16/VITAident#7]
Can you make a possibility to dump a CID in a .txt file ?

With the release of Enso, we need a CID to download the installer and it's the best way to take it in .txt file...

**Comment by joel16** [comment]
Yes that's possible. I'll implement this and release it in a bit. However, this will be a part of the GUI version only since the original version is kept mainly for informational purposes.

**Comment by joel16** [comment]
I have it ready but I need to ask, does enso require you to have the CID with leading zeros for example:

0000000102345669DEADBEEFRANDOMCRAP?

**Comment by DevX-Cipher** [comment]
joel i have some question for you

**Comment by CelesteBlue-dev** [comment]
modz I watch you.

**Comment by DevX-Cipher** [comment]
what does this mean snprintf(idps + (i * 2), (2 * 16) - (i * 2) + 1, "%02X", CID[i]);

**Comment by joel16** [comment]
It's basically printing out two digits of your CID (unsigned ints) onto a char array..
This isn't a support forum.

**Comment by chronoss09** [comment]
For your question Joel16 : yes it does...

**Comment by joel16** [comment]
Available in both GUI and original versions, see https://github.com/joel16/VITAident/releases/tag/0.7.3
