### ISSUE TITLE
Feature request: Support uma0 (sd2vita)

### ISSUE THREAD

**Issue by D-Pyro** [joel16/VITAident#9]

**Comment by joel16** [comment]
What do you mean by support?  Like list storage details of uma0:?

**Comment by D-Pyro** [comment]
Show free space etc

**Comment by joel16** [comment]
Yes I can probably do that for VITAident GUI. Thanks for the suggestion, are you open to testing if I send you a build in the near few days? Because I don't own one.

**Comment by D-Pyro** [comment]
I can test. I have 64Gb memory card, and 64Gb uma0.

**Comment by joel16** [comment]
I'm working on it this week, should have a build ready sometime this week.

**Comment by joel16** [comment]
@D-Pyro can you try this? https://drive.google.com/open?id=0BzIzEQt6k4EEcEpyMzYzcTM0SzA

**Comment by D-Pyro** [comment]
Works great!

**Comment by joel16** [comment]
Thanks for confirming, I'll have the update ready in a bit.
